### PR TITLE
Update BJS for xr utility layer fix

### PR DESCRIPTION
**Pull request by rgerd**
This PR updates the BabylonJS package to [5.17.0](https://github.com/BabylonJS/Babylon.js/releases/tag/5.17.0) to pick up [a change](https://github.com/BabylonJS/Babylon.js/pull/12774) fixing #1087.

### CODE REVIEW

**Review by ryantrem — APPROVED** [review]

**Comment by CedricGuillemet** [comment]
There is a crash with bgfx with D3D12 when creating the vertex array for KHR_texture_transform test scene. It's related to instances but I have no idea why specifically.

**Comment by CedricGuillemet** [comment]
I'm taking a closer look.

**Comment by CedricGuillemet** [comment]
I've found a bug and provided a fix in bgfx : https://github.com/bkaradzic/bgfx/pull/2853

**Comment by CedricGuillemet** [comment]
Fix is merged. I may have to do another PR on bgfx this week. Anyways, I'll update this PR before Friday with bgfx update.

**Pull request merged**
