### PR TITLE
min RT size of 8x8

### PR DESCRIPTION
**Pull request by CedricGuillemet**

### CODE REVIEW

**Review by bghgary — COMMENTED** [review]
Looks okay to me, but probably better for someone else to sign off.

**Review by syntheticmagus — COMMENTED** [review]
+1 to what Gary said. Looks good to me, but I think @ryantrem or @Alex-MSFT are the most knowledgeable about the implications this will have.

**Comment by ryantrem** [comment]
Under what circumstances do we get a 0 width or height?

**Review by ryantrem — APPROVED** [review]

**Comment by CedricGuillemet** [comment]
We get 0 sized window when the engine view is toggled on. I guess the view is created but layout didn't happen yet so  eglQuerySurface(display, surface, EGL_WIDTH/EGL_HEIGHT) returns 0;

**Pull request merged**
