### PR TITLE
Update BabylonNative to consume newer bgfx.cmake submodule commit

### PR DESCRIPTION
**Pull request by chrisfromwork**
We checked in some fixes to bgfx/bx to avoid consuming the windows runtime library in static libs. This change moves us to newer commits that support this fix.

### CODE REVIEW

**Comment by CedricGuillemet** [comment]
bgfx and bgfx.cmake subrepos moved from @syntheticmagus 's repo to babylonjs ones:
https://github.com/BabylonJS/bgfx
https://github.com/BabylonJS/bgfx.cmake

**Comment by chrisfromwork** [comment]
> bgfx and bgfx.cmake subrepos moved from @syntheticmagus 's repo to babylonjs ones:
> https://github.com/BabylonJS/bgfx
> https://github.com/BabylonJS/bgfx.cmake

@CedricGuillemet  does that mean that there are issues with this review?

**Comment by bghgary** [comment]
I think @CedricGuillemet may be referring to the failed builds. GitHub should auto-redirect the repo due to the move, but we should update the links to the BabylonJS one when it's convenient. If you are not in a rush, this PR may be the right one to do it and perhaps it'll fix the build issue also?

**Comment by chrisfromwork** [comment]
> I think @CedricGuillemet may be referring to the failed builds. GitHub should auto-redirect the repo due to the move, but we should update the links to the BabylonJS one when it's convenient. If you are not in a rush, this PR may be the right one to do it and perhaps it'll fix the build issue also?

Up for whatever, but what do these changes entail? Am I needing to update a .gitmodules file?

**Comment by bghgary** [comment]
It requires an update to this file: https://github.com/BabylonJS/bgfx.cmake/blob/master/.gitmodules

**Comment by chrisfromwork** [comment]
@CedricGuillemet  and @bghgary i've moved this to the newest bgfx.cmake commit that contains the .gitmodules fix. We'll see what happens with CI

**Comment by chrisfromwork** [comment]
let's default to @Alex-MSFT's review open elsewhere. they were able to fix CI

**Pull request closed without merging**
