### PR TITLE
add ios deployment targets 12,13,14

### PR DESCRIPTION
**Pull request by CedricGuillemet**
Build deployment targets for iOS 12, 13, 14. Mainly for taking care of deprecated functions.
Waiting https://github.com/BabylonJS/BabylonNative/pull/774 to be merged before.

### CODE REVIEW

**Comment by bghgary** [comment]
How much time is this adding to the overall CI run?

**Comment by CedricGuillemet** [comment]
@bghgary Impossible to say with so few build statistics and with 2 pipelines premature stop.

**Comment by CedricGuillemet** [comment]
FYI @ryantrem @Alex-MSFT 
`'ARHitTestResultType' is deprecated: first deprecated in iOS 14.0`

**Comment by CedricGuillemet** [comment]
@bghgary around 7-8 minutes per new iOS build. We might reduce it a bit (around 1min per build) if git checkout/npm install is done once and all iOS builds done in 1 job. Jobs are done in parallel, so total time addition is not 16minutes.
I still think this is useful with Apple deprecating API quite fast and iOS15 coming soon.

**Review by bghgary — APPROVED** [review]

**Comment by ryantrem** [comment]
> FYI @ryantrem @Alex-MSFT
> `'ARHitTestResultType' is deprecated: first deprecated in iOS 14.0`

Ok, I guess we need to figure this out in order to complete this PR?

**Comment by ryantrem** [comment]
> > FYI @ryantrem @Alex-MSFT
> > `'ARHitTestResultType' is deprecated: first deprecated in iOS 14.0`
> 
> Ok, I guess we need to figure this out in order to complete this PAPR?

It looks like the code already supports both the new APIs and the old APIs, I think we just need to conditionally not compile the old way if we are on 14 or newer. Something similar to what was done here: https://github.com/BabylonJS/BabylonNative/commit/f7327861485be7b377b79053de01eb1799698bb9

**Pull request merged**
