### PR TITLE
Cubemap rendering

### PR DESCRIPTION
**Pull request by CedricGuillemet**
For use with pointlight shadows.
Also fixes invertY for RTT and cubemap loading.

`FrameBuffer` can refer to a 2D Framebuffer or it can holds 6 framebuffers for cubemap. A boolean propery `m_cubeFrameBuffer` is used to determine its nature. 

This PR will be updated once https://github.com/BabylonJS/Babylon.js/pull/10581 is in a new NPM.

### CODE REVIEW

**Comment by bghgary** [comment]
There are build failures. @syntheticmagus How does this change jive with your changes?

**Comment by CedricGuillemet** [comment]
@bghgary @syntheticmagus the shader manipulation part might be removed this week but the framebuffer will stay. Seting PR as draft until I get new BJS with shader flips by Alexis.

**Comment by ryantrem** [comment]
@CedricGuillemet this fixes #398 right?

**Comment by CedricGuillemet** [comment]
@ryantrem yes

**Comment by CedricGuillemet** [comment]
Closing.

**Pull request closed without merging**
