### PR TITLE
Don't set folder property on asio library

### LINKED ISSUE #747: cmake doesn't generate build solution on windows 10
Cmake doesn't generate build solution after installing the new master branch on windows 10

powershell_XV5op7YRbv

### PR DESCRIPTION
**Pull request by rgerd**
asio is a header-only library included as an INTERFACE target, and CMake doesn't allow the FOLDER property to get set on INTERFACE's, so we'll just remove the line.

fixes #747

### CODE REVIEW

**Review by chrisfromwork — APPROVED** [review]

**Comment by bghgary** [comment]
How did this work before?

**Comment by rgerd** [comment]
> How did this work before?

I'm trying to figure that out with the issue OP, but it seems like they might have a weird version of CMake? Or there might be some settings that enable more pedantic error messages?

**Comment by bghgary** [comment]
I see that.

You say above:
> Make doesn't allow the FOLDER property to get set on INTERFACE

It also sounds like this currently works correctly. From the issue you reference in OP.
>  I couldn't get a local repro

I guess I'm a bit confused why it is currently working before this fix.

**Comment by rgerd** [comment]
It only "works" in that it doesn't throw an error when running CMake. I haven't been able to get asio to actually show up in the VS project with that line. So it technically never worked, but it never stopped CMake from running. Tbh I probably just forgot about the line after fiddling with it and just merged it in.

**Pull request merged**
