### PR TITLE
Add Win32 JSI build to CI

### PR DESCRIPTION
**Pull request by rgerd**
Adds Win32 JSI build and validation testing to our CI so we can automatically test JSI usage before sending updates to BabylonReactNative.

### CODE REVIEW

**Comment by bghgary** [comment]
I only see published results for Win32_x86 and Win32_x64. Is there supposed to be JSI version?

**Comment by rgerd** [comment]
@bghgary Good catch, fixed. I'm going to hold off on checking this in until I've tracked down the cause of the teardown bug in the validation tests. Seems like it's slightly non-deterministic and not local to my setup.

**Comment by bghgary** [comment]
I've ran into a crash on shutdown when I fixed the napi-jsi bug.

**Comment by rgerd** [comment]
Waiting on https://github.com/BabylonJS/BabylonNative/pull/868

**Review by rickfromwork — APPROVED** [review]
Code looks good and new JSI tests pass.

**Pull request merged**
