### PR TITLE
vsync Android

### LINKED ISSUE #390: Android frame rate is unlimited
On Android, the render loop goes as fast as it can. With a simple scene, it might render at 300+ FPS. This is rather wasteful, and we should probably initially just hard code it to be limited by vsync or something.

### PR DESCRIPTION
**Pull request by CedricGuillemet**
fixes #390 
bgfx reset flags was not sent to bgfx::reset

### CODE REVIEW

**Review by ryantrem — COMMENTED** [review]
So we don’t have to tie into SurfaceView callback/delegate after all?

**Comment by CedricGuillemet** [comment]
Yep! runs at 60Hz out of the box.

**Comment by ryantrem** [comment]
Nice. Is it a no-op on iOS? And a no-op in XR mode?

**Comment by CedricGuillemet** [comment]
I'm just starting work on iOS and sync rendering.
VSync in XR as well. Got 30FPS with AR.

**Review by ryantrem — APPROVED** [review]

**Pull request merged**
